/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 11 20:11:54 GMT 2022
 */

package org.apache.commons.numbers.angle;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.function.DoubleUnaryOperator;
import org.apache.commons.numbers.angle.Angle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Angle_ESTest extends Angle_ESTest_scaffolding {

 @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DoubleUnaryOperator doubleUnaryOperator0 = Angle.Turn.normalizer(1895.7699968871807);
      double double0 = doubleUnaryOperator0.applyAsDouble(1896.7699968871807);
      ;
}
 @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.of(1471.8);
      Angle.Rad angle_Rad0 = angle_Deg0.toRad();
      ;
}
 @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.of(1471.8);
      Angle.Rad angle_Rad0 = angle_Deg0.toRad();
      ;
}
 @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DoubleUnaryOperator doubleUnaryOperator0 = Angle.Rad.normalizer(2184.99);
      ;
}
 @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of(0.0);
      Angle.Rad angle_Rad0 = Angle.Rad.of((-680.43544088));
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Rad angle_Rad1 = angle_Deg0.toRad();
      boolean boolean0 = angle_Rad1.equals(angle_Rad0);
      ;
}
 @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of(0.0);
      Angle.Rad angle_Rad0 = Angle.Rad.of((-680.43544088));
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Rad angle_Rad1 = angle_Deg0.toRad();
      boolean boolean0 = angle_Rad1.equals(angle_Rad0);
      assertTrue(boolean0);
}
 @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of(0.0);
      Angle.Rad angle_Rad0 = Angle.Rad.of((-680.43544088));
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Rad angle_Rad1 = angle_Deg0.toRad();
      boolean boolean0 = angle_Rad1.equals(angle_Rad0);
      ;
}
 @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
      Angle.Turn angle_Turn0 = angle_Deg0.toTurn();
      Angle.Turn angle_Turn1 = angle_Turn0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
      Angle.Turn angle_Turn0 = angle_Deg0.toTurn();
      Angle.Turn angle_Turn1 = angle_Turn0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.ZERO;
      Angle.Rad angle_Rad0 = angle_Deg0.toRad();
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.ZERO;
      Angle.Rad angle_Rad0 = angle_Deg0.toRad();
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.of((-1443.0014584944388));
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.of((-1443.0014584944388));
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.PI;
      Angle.Rad angle_Rad1 = angle_Rad0.toRad();
      ;
}
 @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of((-3.141592653589793));
      Angle.Rad angle_Rad0 = angle_Turn0.toRad();
      ;
}
 @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of((-3.141592653589793));
      Angle.Rad angle_Rad0 = angle_Turn0.toRad();
      ;
}
 @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      ;
}
 @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      ;
}
 @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of((-1694.988462919987));
      Angle.Rad angle_Rad0 = angle_Turn0.toRad();
      Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
      ;
}
 @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.PI;
      double double0 = angle_Rad0.getAsDouble();
      ;
}
 @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of((-3.141592653589793));
      double double0 = angle_Turn0.getAsDouble();
      ;
}
 @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.ZERO;
      double double0 = angle_Deg0.WITHIN_0_AND_360.applyAsDouble(6.283185307179586);
      ;
}
 @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DoubleUnaryOperator doubleUnaryOperator0 = Angle.Deg.normalizer((-809.953167421288));
      double double0 = doubleUnaryOperator0.applyAsDouble(6.283185307179586);
      ;
}
 @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of((-1694.988462919987));
      double double0 = angle_Turn0.WITHIN_0_AND_1.applyAsDouble((-197.28762177193));
      ;
}
 @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.of((-1694.988462919987));
      double double0 = angle_Turn0.WITHIN_0_AND_1.applyAsDouble((-197.28762177193));
      ;
}
 @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      Angle.Turn angle_Turn1 = Angle.Turn.of(1.5707963267948966);
      boolean boolean0 = angle_Turn0.equals(angle_Turn1);
      ;
}
 @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      Angle.Turn angle_Turn1 = Angle.Turn.of(1.5707963267948966);
      boolean boolean0 = angle_Turn0.equals(angle_Turn1);
      ;
}
 @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      Angle.Turn angle_Turn1 = Angle.Turn.of(1.5707963267948966);
      boolean boolean0 = angle_Turn0.equals(angle_Turn1);
      assertTrue(boolean0);
}
 @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      Angle.Turn angle_Turn1 = Angle.Turn.of(1.5707963267948966);
      boolean boolean0 = angle_Turn0.equals(angle_Turn1);
      ;
}
 @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      boolean boolean0 = angle_Turn0.equals(angle_Turn0);
      ;
}
 @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      boolean boolean0 = angle_Turn0.equals(angle_Turn0);
      assertTrue(boolean0);
}
 @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      boolean boolean0 = angle_Turn0.equals(angle_Turn0);
      ;
}
 @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.PI;
      Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
      boolean boolean0 = angle_Deg0.equals(angle_Rad0.WITHIN_0_AND_2PI);
      ;
}
 @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.PI;
      Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
      boolean boolean0 = angle_Deg0.equals(angle_Rad0.WITHIN_0_AND_2PI);
      assertTrue(boolean0);
}
 @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.PI;
      Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
      boolean boolean0 = angle_Deg0.equals(angle_Rad0.WITHIN_0_AND_2PI);
      ;
}
 @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      boolean boolean0 = angle_Rad0.equals((Object) null);
      assertTrue(boolean0);
}
 @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.ZERO;
      Angle.Rad angle_Rad0 = angle_Deg0.toRad();
      double double0 = angle_Rad0.getAsDouble();
      ;
}
 @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Angle.Deg angle_Deg0 = Angle.Deg.ZERO;
      Angle.Rad angle_Rad0 = angle_Deg0.toRad();
      double double0 = angle_Rad0.getAsDouble();
      ;
}
 @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Deg angle_Deg1 = angle_Deg0.toDeg();
      ;
}
 @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Deg angle_Deg1 = angle_Deg0.toDeg();
      ;
}
 @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DoubleUnaryOperator doubleUnaryOperator0 = Angle.Rad.normalizer(1.5707963267948966);
      double double0 = doubleUnaryOperator0.applyAsDouble(1.5707963267948966);
      ;
}
 @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.PI;
      Angle.Rad angle_Rad1 = angle_Rad0.toRad();
      ;
}
 @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Turn angle_Turn1 = angle_Deg0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
      Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
      Angle.Turn angle_Turn1 = angle_Deg0.toTurn();
      ;
}
 @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      angle_Turn0.hashCode();
      ;
}
 @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Angle.Rad angle_Rad0 = Angle.Rad.TWO_PI;
      Angle.Turn angle_Turn0 = angle_Rad0.toTurn();
      angle_Turn0.hashCode();
      ;
}
}
