/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 10 18:17:56 GMT 2022
 */

package org.apache.commons.lang3.builder;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Arrays;
import org.apache.commons.lang3.builder.MultilineRecursiveToStringStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MultilineRecursiveToStringStyle_ESTest extends MultilineRecursiveToStringStyle_ESTest_scaffolding {

 @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      assertNotNull(multilineRecursiveToStringStyle0);
}
 @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      char[] charArray0 = new char[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "]90^(chjW!&K<Eiim&", charArray0);
      ;
}
 @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      char[] charArray0 = new char[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "]90^(chjW!&K<Eiim&", charArray0);
      ;
}
 @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      char[] charArray0 = new char[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "]90^(chjW!&K<Eiim&", charArray0);
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      char[] charArray0 = new char[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "]90^(chjW!&K<Eiim&", charArray0);
      ;
}
 @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      ;
}
 @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      boolean[] booleanArray0 = new boolean[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "", booleanArray0);
      ;
}
 @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      boolean[] booleanArray0 = new boolean[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "", booleanArray0);
      ;
}
 @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      boolean[] booleanArray0 = new boolean[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "", booleanArray0);
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      boolean[] booleanArray0 = new boolean[3];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "", booleanArray0);
      ;
}
 @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("q%b66y,?~&_Q4E");
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("q%b66y,?~&_Q4E");
      ;
}
 @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("q%b66y,?~&_Q4E");
      ;
}
 @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("q%b66y,?~&_Q4E");
      short[] shortArray0 = new short[23];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "q%b66y,?~&_Q4E", shortArray0);
      ;
}
 @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("q%b66y,?~&_Q4E");
      short[] shortArray0 = new short[23];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "q%b66y,?~&_Q4E", shortArray0);
      ;
}
 @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("q%b66y,?~&_Q4E");
      short[] shortArray0 = new short[23];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "q%b66y,?~&_Q4E", shortArray0);
      ;
}
 @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      assertNotNull(multilineRecursiveToStringStyle0);
}
 @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      float[] floatArray0 = new float[2];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "@U}", floatArray0);
      ;
}
 @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      float[] floatArray0 = new float[2];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "@U}", floatArray0);
      ;
}
 @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      float[] floatArray0 = new float[2];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "@U}", floatArray0);
      ;
}
 @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      float[] floatArray0 = new float[2];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "@U}", floatArray0);
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SEJS5");
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SEJS5");
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SEJS5");
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "<size=");
      ;
}
 @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "<size=");
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "<size=");
      ;
}
 @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      assertNotNull(multilineRecursiveToStringStyle0);
}
 @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      ;
}
 @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      ;
}
 @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      ;
}
 @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("7nNa1C");
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("7nNa1C");
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("7nNa1C");
      ;
}
 @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      ;
}
 @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      Boolean boolean0 = new Boolean("");
      assertTrue(boolean0);
}
 @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      Boolean boolean0 = new Boolean("");
      ;
}
 @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      Boolean boolean0 = new Boolean("");
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "mKv^ETi_1", boolean0);
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SJ5");
      Boolean boolean0 = new Boolean("");
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "mKv^ETi_1", boolean0);
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      assertNotNull(multilineRecursiveToStringStyle0);
}
 @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      String string0 = ".xnXTQj<C>\\u)>";
      StringBuffer stringBuffer0 = new StringBuffer(string0);
      ;
}
 @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      String string0 = ".xnXTQj<C>\\u)>";
      StringBuffer stringBuffer0 = new StringBuffer(string0);
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      String string0 = ".xnXTQj<C>\\u)>";
      StringBuffer stringBuffer0 = new StringBuffer(string0);
      ;
}
 @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      String string0 = ".xnXTQj<C>\\u)>";
      StringBuffer stringBuffer0 = new StringBuffer(string0);
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "S", "S");
      assertEquals(0, stringBuffer0.length());
}
 @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      String string0 = ".xnXTQj<C>\\u)>";
      StringBuffer stringBuffer0 = new StringBuffer(string0);
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "S", "S");
      ;
}
 @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "<", stringBuffer0);
      ;
}
 @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      assertNotNull(multilineRecursiveToStringStyle0);
}
 @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      ;
}
 @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) multilineRecursiveToStringStyle0;
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, (String) null, objectArray0);
      ;
}
 @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("]j8K#bl");
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) multilineRecursiveToStringStyle0;
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, (String) null, objectArray0);
      ;
}
 @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      byte[] byteArray0 = new byte[9];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "mA", byteArray0);
      ;
}
 @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      byte[] byteArray0 = new byte[9];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "mA", byteArray0);
      ;
}
 @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      byte[] byteArray0 = new byte[9];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "mA", byteArray0);
      ;
}
 @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      byte[] byteArray0 = new byte[9];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "mA", byteArray0);
      ;
}
 @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      ;
}
 @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertEquals(multilineRecursiveToStringStyle0, stringBuffer0);
}
 @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      assertNotNull(stringBuffer0.toString());
}
 @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer();
      ;
}
 @Test(timeout = 4000)
  public void test98()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer(0);
      // Undeclared exception!
      try { 
        multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "", (short[]) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.builder.ToStringStyle", e);
      }
  }
 @Test(timeout = 4000)
  public void test99()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("!|;|(<");
      double[] doubleArray0 = new double[4];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "!|;|(<", doubleArray0);
      ;
}
 @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("!|;|(<");
      double[] doubleArray0 = new double[4];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "!|;|(<", doubleArray0);
      ;
}
 @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("!|;|(<");
      int[] intArray0 = new int[4];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "!|;|(<", intArray0);
      ;
}
 @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("!|;|(<");
      int[] intArray0 = new int[4];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "!|;|(<", intArray0);
      ;
}
 @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      boolean[] booleanArray0 = new boolean[6];
      // Undeclared exception!
      try { 
        multilineRecursiveToStringStyle0.appendDetail((StringBuffer) null, (String) null, booleanArray0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.builder.ToStringStyle", e);
      }
  }
 @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("!|;|(<");
      long[] longArray0 = new long[6];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "!|;|(<", longArray0);
      ;
}
 @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("!|;|(<");
      long[] longArray0 = new long[6];
      multilineRecursiveToStringStyle0.appendDetail(stringBuffer0, "!|;|(<", longArray0);
      ;
}
 @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      MultilineRecursiveToStringStyle multilineRecursiveToStringStyle0 = new MultilineRecursiveToStringStyle();
      StringBuffer stringBuffer0 = new StringBuffer("y[qCDv>>8$SEJS5");
      // Undeclared exception!
      try { 
        multilineRecursiveToStringStyle0.reflectionAppendArrayDetail(stringBuffer0, "", multilineRecursiveToStringStyle0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
         //
         // Argument is not an array
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }
}
