/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 10 23:49:22 GMT 2022
 */

package org.apache.commons.imaging.color;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.imaging.color.ColorCmyk;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ColorCmyk_ESTest extends ColorCmyk_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ColorCmyk colorCmyk0 = new ColorCmyk((-328.1414822), (-328.1414822), (-328.1414822), (-1352.83));
      colorCmyk0.hashCode();
      assertEquals((-1352.83), colorCmyk0.K, 0.01);
      assertEquals((-328.1414822), colorCmyk0.Y, 0.01);
      assertEquals((-328.1414822), colorCmyk0.M, 0.01);
      assertEquals((-328.1414822), colorCmyk0.C, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.RED;
      colorCmyk0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.RED;
      ColorCmyk colorCmyk1 = ColorCmyk.MAGENTA;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(boolean0);
      assertFalse(colorCmyk1.equals((Object)colorCmyk0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.GREEN;
      ColorCmyk colorCmyk1 = new ColorCmyk(100.0, 0.0, 100.0, 0.0);
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.YELLOW;
      ColorCmyk colorCmyk1 = ColorCmyk.RED;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(colorCmyk1.equals((Object)colorCmyk0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.RED;
      ColorCmyk colorCmyk1 = ColorCmyk.BLACK;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.BLUE;
      ColorCmyk colorCmyk1 = ColorCmyk.BLACK;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.BLUE;
      String string0 = colorCmyk0.toString();
      assertEquals("{C: 100.0, M: 100.0, Y: 0.0, K: 0.0}", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.RED;
      String string0 = colorCmyk0.toString();
      assertEquals("{C: 0.0, M: 100.0, Y: 100.0, K: 0.0}", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.MAGENTA;
      ColorCmyk colorCmyk1 = ColorCmyk.RED;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(colorCmyk1.equals((Object)colorCmyk0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.RED;
      ColorCmyk colorCmyk1 = ColorCmyk.YELLOW;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(boolean0);
      assertFalse(colorCmyk1.equals((Object)colorCmyk0));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.BLACK;
      ColorCmyk colorCmyk1 = ColorCmyk.YELLOW;
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.MAGENTA;
      ColorCmyk colorCmyk1 = new ColorCmyk(100.0, 0.0, 100.0, 0.0);
      boolean boolean0 = colorCmyk0.equals(colorCmyk1);
      assertFalse(boolean0);
      assertEquals(0.0, colorCmyk1.M, 0.01);
      assertEquals(100.0, colorCmyk1.C, 0.01);
      assertEquals(0.0, colorCmyk1.K, 0.01);
      assertEquals(100.0, colorCmyk1.Y, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.MAGENTA;
      boolean boolean0 = colorCmyk0.equals("{C: 0.0, M: 100.0, Y: 100.0, K: 0.0}");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.BLACK;
      boolean boolean0 = colorCmyk0.equals(colorCmyk0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.BLUE;
      boolean boolean0 = colorCmyk0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ColorCmyk colorCmyk0 = ColorCmyk.BLUE;
      colorCmyk0.hashCode();
  }
}
